### ISSUE TITLE
Ditch JavaScript, use plain old HTML

### ISSUE THREAD

**Issue by Larivact** [omnirom/omni-website#37]
Yes React makes the site snappy but I don't think this justifies making the site inaccessible for anyone not running JavaScript. There is no reason the site couldn't just be four HTML files.

Using React, Redux, React Router, Webpack, Jest and Lodash for a four page site containing only text and some images is over engineering at the cost of accessibility.

Some side notes:
You directly serve your repository (which is why one can access https://www.omnirom.org/README.md).
You fail to return not found pages (https://www.omnirom.org/test).
You committed the `dist` directory.

I'd be willing to rewrite the current site with plain old HTML, to be accessible while still looking like it currently does, but only if you will accept it.

**Comment by jerdog** [comment]
You have valid points - this is the direction we chose to go. 
To your other notes:
- the directly served repo is part of our choice due to tech used. In the future we can look at a few other things to avoid this
- great catch on 404 pages. why not create one and submit it as a PR?
- the `dist` directory is where the site resides and how this works

@golden-guy  and @rgualberto can provide more info

**Comment by Larivact** [comment]
>You have valid points - this is the direction we chose to go.

So that's a no? ... without any justification?
>great catch on 404 pages. why not create one and submit it as a PR?

I proposed to remove the JavaScript, I am not interested in changing it.

>the directly served repo is part of our choice due to tech used. [...]
>the dist directory is where the site resides and how this works

It is amateurish. You are supposed to have the source code – and only the source code – under version control. Then from the source code you build / generate the files you deploy. You however directly serve the repository and commit build artifacts to source control.

**Comment by rgualberto** [comment]
Just my 2 cents but I'll address your points as I see them.

While I see where you're coming from, I believe you are over exaggerating the 'accessibility' point.
Firstly, your definition of accessible seems to center around javascript disabled clients only. Yes, you are correct in that there is no fallback for no-js. Yes progressive enhancement dictates there should be a fallback. But, in my opinion, the user base coming to checkout omni-rom is not generally running old browsers that don't support it. Nor do I think that those disabling it for security reasons cant temporarily enable it to see if they so choose to do it. It's reasonable to assume a tech-savvy user base. Also it's 2017; It's not unreasonable to have an expectation of enabled JS.

Secondly, the site is partially accessible (in the official sense of the word) but can be made to be fully accessible if you so choose to develop it. You could accomplish this faster with the existing structure than tearing it down and starting from scratch. This is simply because accessibility largely revolves around output markup structure/attribute manipulation and not JS. 

Finally, its just plain easier to develop when a scaffolding is in place. Moving forward, any additional changes to the base site is trivial. Backpedaling to pure markup/css will just make changing things more annoying. Might as well opt for a CMS at that point. 

On another note, I believe you are trivializing just how much work would be involved in reaching full parity with your approach. I also sense a misunderstanding of the toolset you felt compelled to list since you attempt to use them as an argument against JS. In this regard, I'd appreciate it if you made your case rather than just using them as a scapegoat.

As for the rest:
- Creating a 404 page would be trivial. Add a catch all route in the router and point it to the page
- Committing the dist directory was a choice made to simplify deployment for anyone planning to contribute. It can easily be taken out if someone else wants the responsibility of curating the deploys.
- Being able to access the readme/other files in the root is indeed a side effect of just pushing the repo up. Again, we can tighten up the deploy process/server settings and address this.

Let me know if you disagree and I'd be happy to continue this discussion.

**Comment by ddrager** [comment]
Closing this issue, remaining a react repo.
